"use strict";
// Render a fight + its wipe summary as Discord-ready markdown.
import { mmss, num } from "./format.js";

export function toDiscordMarkdown(fight, summary) {
  const lines = [];
  const result = summary.kill ? "Kill" : "Wipe";
  lines.push(`## ${fight.bossName} — ${result} (${mmss(fight.durationMs)})`);
  lines.push("");

  if (summary.kill) {
    lines.push("**Clean pull — boss down.** 🎉");
    return lines.join("\n");
  }

  lines.push(`**Primary cause:** ${summary.primaryCause.text}`);

  if (summary.primaryCause.evidence?.length) {
    lines.push("");
    lines.push("**Evidence:**");
    for (const e of summary.primaryCause.evidence) lines.push(`- ${e}`);
  }

  const topDeaths = summary.deaths.slice(0, 5);
  if (topDeaths.length) {
    lines.push("");
    lines.push("**Deaths:**");
    for (const d of topDeaths) {
      const blow = d.killingBlow ? ` — ${d.killingBlow.abilityName} (${num(d.killingBlow.amount)})` : "";
      lines.push(`- ${mmss(d.timestamp)} **${d.victim.name}**${blow}`);
    }
  }

  if (summary.contributingFactors.length) {
    lines.push("");
    lines.push("**Contributing factors:**");
    for (const f of summary.contributingFactors) lines.push(`- ${f.text}`);
  }

  const mechanics = (summary.mechanics ?? []).slice(0, 5);
  if (mechanics.length) {
    lines.push("");
    lines.push("**Avoidable mechanics:**");
    for (const m of mechanics) {
      const deathTxt = m.deaths > 0 ? ` — **${m.deaths} death${m.deaths > 1 ? "s" : ""}**` : "";
      lines.push(`- ${m.ability}: ${m.playersHit} hit, ${num(m.totalDamage)} dmg${deathTxt}`);
    }
  }

  if (summary.nextPullChecklist.length) {
    lines.push("");
    lines.push("**Fix next pull:**");
    summary.nextPullChecklist.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
  }

  lines.push("");
  lines.push(`_Confidence: ${summary.confidence} · generated by CSI: TBC_`);
  return lines.join("\n");
}
