"use strict";
// AUTO-GENERATED by scripts/gen-rule-ids.mjs — do not edit by hand.
// Ability game ID -> mechanic-catalogue key (see RULES in rules.js), harvested
// from per-encounter DamageTaken tables of 30 live Anniversary reports
// (35 encounters) on 2026-09-03. IDs are the primary lookup; name matching
// stays as the fallback for ranks/bosses not present in the harvested logs.
export const RULE_SPELL_IDS = {
  40481: "acidic wound", // Gurtogg Bloodboil · 3 reports
  32014: "air burst", // Archimonde · 3 reports
  29973: "arcane explosion", // Shade of Aran · 1 report
  33237: "arcane explosion", // High King Maulgar · 3 reports
  34190: "arcane orb", // Void Reaver · 3 reports
  28168: "arcing smash", // High King Maulgar, The Lurker Below · 6 reports
  39144: "arcing smash", // High King Maulgar · 3 reports
  40457: "arcing smash", // Gurtogg Bloodboil · 3 reports
  41337: "aura of anger", // Reliquary of Souls · 2 reports
  30613: "blast nova", // Magtheridon · 1 report
  33061: "blast wave", // High King Maulgar · 3 reports
  33009: "blinding light", // High Astromancer Solarian · 1 report
  29951: "blizzard", // Shade of Aran · 2 reports
  42005: "bloodboil", // Gurtogg Bloodboil · 3 reports
  31306: "carrion swarm", // Anetheron · 3 reports
  38441: "cataclysmic bolt", // Fathom-Lord Karathress · 3 reports
  36240: "cave in", // Gruul the Dragonkiller · 3 reports
  37675: "chaos blast", // Leotheras the Blind · 3 reports
  30129: "charred earth", // Nightbane · 3 reports
  15284: "cleave", // Shade of Akama · 1 report
  30131: "cleave", // Nightbane · 3 reports
  30619: "cleave", // Magtheridon · 2 reports
  31043: "cleave", // Opera Hall · 2 reports
  31345: "cleave", // Azgalor · 3 reports
  38260: "cleave", // Lady Vashj · 3 reports
  30757: "conflagration", // Magtheridon · 2 reports
  37018: "conflagration", // Kael'thas Sunstrider · 2 reports
  20924: "consecration", // Kael'thas Sunstrider · 1 report
  30817: "deadly swathe", // Opera Hall · 1 report
  31258: "death & decay", // Rage Winterchill · 3 reports
  41978: "debilitating poison", // Shade of Akama · 1 report
  41178: "debilitating strike", // Shade of Akama · 3 reports
  30631: "debris", // Magtheridon · 1 report
  36449: "debris", // Magtheridon · 2 reports
  31944: "doomfire", // Archimonde · 3 reports
  31969: "doomfire", // Archimonde · 3 reports
  37764: "earthquake", // Morogrim Tidewalker · 3 reports
  40486: "eject", // Gurtogg Bloodboil · 3 reports
  40597: "eject", // Gurtogg Bloodboil · 3 reports
  40871: "fatal attraction", // Mother Shahraz · 1 report
  40599: "fel arcing smash", // Gurtogg Bloodboil · 3 reports
  40593: "fel geyser", // Gurtogg Bloodboil · 3 reports
  40508: "fel-acid breath", // Gurtogg Bloodboil · 2 reports
  40595: "fel-acid breath", // Gurtogg Bloodboil · 3 reports
  34121: "flame buffet", // Al'ar · 3 reports
  35383: "flame patch", // Al'ar · 3 reports
  34287: "flame quills", // Al'ar · 1 report
  38145: "forked lightning", // Lady Vashj · 3 reports
  31250: "frost nova", // Rage Winterchill · 3 reports
  36989: "frost nova", // Kael'thas Sunstrider · 2 reports
  37478: "geyser", // The Lurker Below · 3 reports
  31972: "grip of the legion", // Archimonde · 2 reports
  30383: "hateful bolt", // The Curator · 3 reports
  41926: "hateful strike", // Supremus · 3 reports
  29522: "holy fire", // Maiden of Virtue · 3 reports
  29563: "holy fire", // carried from a previous harvest
  29512: "holy ground", // Maiden of Virtue · 3 reports
  32445: "holy wrath", // Maiden of Virtue · 3 reports
  33813: "hurtful strike", // Gruul the Dragonkiller · 3 reports
  31249: "icebolt", // Rage Winterchill · 3 reports
  20153: "immolation", // Prince Malchezaar · 1 report
  31303: "immolation", // Anetheron · 3 reports
  39837: "impaling spine", // High Warlord Naj'entus · 3 reports
  31302: "inferno effect", // Anetheron · 3 reports
  31436: "malevolent cleave", // Kaz'rogal · 3 reports
  31447: "mark of kaz'rogal", // Kaz'rogal · 3 reports
  31463: "mark of kaz'rogal", // Kaz'rogal · 3 reports
  35410: "melt armor", // Al'ar · 1 report
  40265: "molten flame", // Supremus · 3 reports
  39835: "needle spine", // High Warlord Naj'entus · 3 reports
  39968: "needle spine explosion", // High Warlord Naj'entus · 3 reports
  30523: "nether burn", // Netherspite · 3 reports
  35859: "nether vapor", // Kael'thas Sunstrider · 2 reports
  34164: "pounding", // Void Reaver · 3 reports
  36819: "pyroblast", // Kael'thas Sunstrider · 1 report
  37091: "rain of bones", // Nightbane · 3 reports
  31340: "rain of fire", // Azgalor · 3 reports
  42023: "rain of fire", // Shade of Akama · 3 reports
  36297: "reverberation", // Gruul the Dragonkiller · 2 reports
  40810: "saber lash", // Mother Shahraz · 1 report
  37284: "scalding water", // The Lurker Below · 3 reports
  38445: "sear nova", // Fathom-Lord Karathress · 3 reports
  30510: "shadow bolt volley", // Magtheridon · 2 reports
  29832: "shadow cleave", // Attumen the Huntsman · 3 reports
  30852: "shadow nova", // Prince Malchezaar · 2 reports
  33671: "shatter", // Gruul the Dragonkiller · 3 reports
  38509: "shock blast", // Lady Vashj · 3 reports
  40859: "sinister beam", // Mother Shahraz · 1 report
  30210: "smoldering breath", // Nightbane · 3 reports
  32053: "soul charge", // Archimonde · 1 report
  32054: "soul charge", // Archimonde · 2 reports
  32057: "soul charge", // Archimonde · 2 reports
  41545: "soul scream", // Reliquary of Souls · 2 reports
  41426: "spirit shock", // Reliquary of Souls · 1 report
  41377: "spite", // Reliquary of Souls · 2 reports
  37433: "spout", // The Lurker Below · 3 reports
  38281: "static charge", // Lady Vashj · 3 reports
  25653: "tail sweep", // Nightbane · 2 reports
  39878: "tidal burst", // High Warlord Naj'entus · 3 reports
  37730: "tidal wave", // Morogrim Tidewalker · 3 reports
  360327: "toxic spores", // Lady Vashj · 3 reports
  31341: "unquenchable flames", // Azgalor · 3 reports
  40860: "vile beam", // Mother Shahraz · 1 report
  38246: "vile sludge", // Hydross the Unstable · 3 reports
  42052: "volcanic geyser", // Supremus · 3 reports
  31408: "war stomp", // Azgalor · 3 reports
  31480: "war stomp", // Kaz'rogal · 3 reports
  38235: "water tomb", // Hydross the Unstable · 3 reports
  38028: "watery grave", // Morogrim Tidewalker · 3 reports
  15589: "whirlwind", // Moroes · 2 reports
  33239: "whirlwind", // High King Maulgar · 3 reports
  36982: "whirlwind", // Kael'thas Sunstrider · 2 reports
  37641: "whirlwind", // Leotheras the Blind · 3 reports
  40861: "wicked beam", // Mother Shahraz · 1 report
  42783: "wrath of the astromancer", // High Astromancer Solarian · 1 report
  42787: "wrath of the astromancer", // High Astromancer Solarian · 1 report
};
