"use strict";
// AUTO-GENERATED by scripts/gen-rule-ids.mjs — do not edit by hand.
// Ability game ID -> mechanic-catalogue key (see RULES in rules.js), harvested
// from per-encounter DamageTaken tables of 22 live Anniversary reports
// (22 encounters) on 2026-07-07. IDs are the primary lookup; name matching
// stays as the fallback for ranks/bosses not present in the harvested logs.
export const RULE_SPELL_IDS = {
  29973: "arcane explosion", // Shade of Aran · 1 report
  33237: "arcane explosion", // High King Maulgar · 1 report
  34190: "arcane orb", // Void Reaver · 3 reports
  28168: "arcing smash", // High King Maulgar, The Lurker Below · 3 reports
  39144: "arcing smash", // High King Maulgar · 3 reports
  30613: "blast nova", // Magtheridon · 2 reports
  33061: "blast wave", // High King Maulgar · 2 reports
  33009: "blinding light", // High Astromancer Solarian · 3 reports
  29951: "blizzard", // Shade of Aran · 3 reports
  38441: "cataclysmic bolt", // Fathom-Lord Karathress · 3 reports
  36240: "cave in", // Gruul the Dragonkiller · 3 reports
  37675: "chaos blast", // Leotheras the Blind · 3 reports
  30129: "charred earth", // Nightbane · 3 reports
  30131: "cleave", // Nightbane · 3 reports
  30619: "cleave", // Magtheridon · 3 reports
  31043: "cleave", // Opera Hall · 1 report
  38260: "cleave", // Lady Vashj · 3 reports
  30757: "conflagration", // Magtheridon · 3 reports
  37018: "conflagration", // Kael'thas Sunstrider · 3 reports
  30817: "deadly swathe", // Opera Hall · 2 reports
  30631: "debris", // Magtheridon · 1 report
  36449: "debris", // Magtheridon · 3 reports
  37764: "earthquake", // Morogrim Tidewalker · 3 reports
  34121: "flame buffet", // Al'ar · 2 reports
  35383: "flame patch", // Al'ar · 2 reports
  38145: "forked lightning", // Lady Vashj · 3 reports
  37478: "geyser", // The Lurker Below · 3 reports
  30383: "hateful bolt", // The Curator · 3 reports
  29522: "holy fire", // Maiden of Virtue · 3 reports
  29563: "holy fire", // Moroes · 3 reports
  29512: "holy ground", // Maiden of Virtue · 3 reports
  32445: "holy wrath", // Maiden of Virtue · 3 reports
  33813: "hurtful strike", // Gruul the Dragonkiller · 3 reports
  30523: "nether burn", // Netherspite · 3 reports
  35859: "nether vapor", // Kael'thas Sunstrider · 3 reports
  34164: "pounding", // Void Reaver · 3 reports
  37091: "rain of bones", // Nightbane · 3 reports
  36297: "reverberation", // Gruul the Dragonkiller · 3 reports
  37284: "scalding water", // The Lurker Below · 3 reports
  38445: "sear nova", // Fathom-Lord Karathress · 3 reports
  30510: "shadow bolt volley", // Magtheridon · 3 reports
  29832: "shadow cleave", // Attumen the Huntsman · 3 reports
  33671: "shatter", // Gruul the Dragonkiller · 3 reports
  38509: "shock blast", // Lady Vashj · 3 reports
  30210: "smoldering breath", // Nightbane · 3 reports
  37433: "spout", // The Lurker Below · 3 reports
  38281: "static charge", // Lady Vashj · 3 reports
  25653: "tail sweep", // Nightbane · 1 report
  37730: "tidal wave", // Morogrim Tidewalker · 3 reports
  360327: "toxic spores", // Lady Vashj · 3 reports
  38246: "vile sludge", // Hydross the Unstable · 2 reports
  38235: "water tomb", // Hydross the Unstable · 3 reports
  38028: "watery grave", // Morogrim Tidewalker · 1 report
  15589: "whirlwind", // Moroes · 1 report
  36982: "whirlwind", // Kael'thas Sunstrider · 3 reports
  37641: "whirlwind", // Leotheras the Blind · 3 reports
  42783: "wrath of the astromancer", // High Astromancer Solarian · 2 reports
  42787: "wrath of the astromancer", // High Astromancer Solarian · 3 reports
};
